### ISSUE TITLE
It is blocking the event loop

### ISSUE THREAD

**Issue by gitSambhal** [algoan/pubsub#373]
I am using Google Pubsub in NestJs and when the data is recieved by the handler, the event loop gets blocked and I am unable to make any HTTP request to the API.
I am using [Blocked At](https://github.com/naugtur/blocked-at) plugin to get the following stacktrace.
```
Blocked for 20320.787875ms, operation started here: [
  '    at AsyncHook.init (/Users/username/myproject/node_modules/.pnpm/blocked-at@1.2.0/node_modules/blocked-at/index.js:31:11)',
  '    at emitInitNative (node:internal/async_hooks:202:43)',
  '    at emitInitScript (node:internal/async_hooks:505:3)',
  '    at promiseInitHook (node:internal/async_hooks:324:3)',
  '    at promiseInitHookWithDestroyTracking (node:internal/async_hooks:328:3)',
  '    at /Users/username/myproject/node_modules/.pnpm/@nestjs+microservices@9.0.11_3xexfhuxzzpm44flufjnppzrlu/node_modules/@nestjs/microservices/context/rpc-context-creator.js:43:23',
  '    at InterceptorsConsumer.intercept (/Users/username/myproject/node_modules/.pnpm/@nestjs+core@9.0.11_kj7rymkcr5lkprk6tswpsa5dxa/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:11:20)',
  '    at /Users/username/myproject/node_modules/.pnpm/@nestjs+microservices@9.0.11_3xexfhuxzzpm44flufjnppzrlu/node_modules/@nestjs/microservices/context/rpc-context-creator.js:51:46',
  '    at /Users/username/myproject/node_modules/.pnpm/@nestjs+microservices@9.0.11_3xexfhuxzzpm44flufjnppzrlu/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:38',
  '    at eventHandler (/Users/username/myproject/node_modules/.pnpm/@nestjs+microservices@9.0.11_3xexfhuxzzpm44flufjnppzrlu/node_modules/@nestjs/microservices/listeners-controller.js:55:53)',
  '    at Object.onMessage (/Users/username/myproject/node_modules/.pnpm/@algoan+nestjs-google-pubsub-microservice@3.0.4_o2upt3vfiv5amp3ncoauuaj7la/node_modules/@algoan/nestjs-google-pubsub-microservice/src/GooglePubSubServer.ts:110:13)',
  '    at Subscription.<anonymous> (/Users/username/myproject/node_modules/.pnpm/@algoan+pubsub@4.6.3/node_modules/@algoan/pubsub/dist/src/GoogleCloudPubSub/GoogleCloudPubSub.js:33:22)',
  '    at Subscription.emit (node:events:513:28)',
  '    at Subscriber.<anonymous> (/Users/username/myproject/node_modules/.pnpm/@google-cloud+pubsub@2.19.4/node_modules/@google-cloud/pubsub/src/subscription.ts:329:38)',
  '    at Subscriber.emit (node:events:513:28)',
  '    at /Users/username/myproject/node_modules/.pnpm/@google-cloud+pubsub@2.19.4/node_modules/@google-cloud/pubsub/src/lease-manager.ts:243:47',
  '    at processTicksAndRejections (node:internal/process/task_queues:77:11)'
]
```

**Comment by ccoeurderoy** [comment]
Hey @gitSambhal,

Could you share a repo so we can reproduce your error please? 

Thanks in advance

**Comment by ccoeurderoy** [comment]
Ok I'm closing this issue then!
